# Generated by Django 5.1.1 on 2024-09-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccountManager', '0003_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(default='local', max_length=60),
        ),
    ]
