# Generated by Django 5.1.6 on 2025-02-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccountManager', '0004_alter_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
