# Generated by Django 5.1.6 on 2025-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccountManager', '0005_user_google_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_access_token',
            field=models.CharField(max_length=256),
        ),
    ]
